# https://github.com/anishathalye/dotbot

- clean: ['~']

# Common dotfiles
- defaults:
    link:
      create: true
      relink: true

- link:
    # bash
    ~/.bash_aliases: bash/bash_aliases.sh
    ~/.bash_profile: bash/bash_profile.sh
    ~/.bash_prompt: bash/bash_prompt.sh
    ~/.bashrc: bash/bashrc.sh
    ~/.profile: bash/profile.sh
    # editorconfig
    ~/.editorconfig: editorconfig/editorconfig
    # git
    ~/.gitconfig: git/gitconfig
    # zsh
    ~/.zprofile: zsh/zprofile
    ~/.zshrc: zsh/zshrc

# Apple macOS specific dotfiles
- defaults:
    link:
      if: '[ "$(uname)" = "Darwin" ]'

- link:
    # git
    ~/.gitignore_global:
      path: gitignore/Global/macOS.gitignore
    # karabiner-elements
    ~/.config/karabiner: karabiner

# Linux specific dotfiles
- defaults:
    link:
      if: '[ "$(uname)" = "Linux" ]'

- link:
    # git
    ~/.gitignore_global:
      path: gitignore/Global/Linux.gitignore
