# Aliases
alias cls="clear"
alias ll="ls -alh"
alias lld="ls -adlh"
alias llr="ls -lRath"
alias more="\${PAGER:-more}"

# Shell history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=$HISTSIZE
setopt BANG_HIST                    # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY             # Write the history file in the ":start:elapsed;command" format.
setopt APPEND_HISTORY               # Append history to history file.
#setopt INC_APPEND_HISTORY           # Write to the history file immediately, not when the shell exits.
#setopt SHARE_HISTORY                # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST       # Expire duplicate entries first when trimming history.
#setopt HIST_IGNORE_DUPS             # Don't record an entry that was just recorded again.
#setopt HIST_IGNORE_ALL_DUPS         # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS            # Do not display a line previously found.
#setopt HIST_IGNORE_SPACE            # Don't record an entry starting with a space.
#setopt HIST_SAVE_NO_DUPS            # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS           # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY                  # Don't execute immediately upon history expansion.
#setopt HIST_BEEP                    # Beep when accessing nonexistent history.

# Unified control keys
bindkey "^[[H" beginning-of-line    # Fn+Left
bindkey "^[[F" end-of-line          # Fn+Right

# Smart history search
#bindkey "^[[A" history-beginning-search-backward
#bindkey "^[[B" history-beginning-search-forward
autoload -U history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^[[A" history-beginning-search-backward-end    # Up
bindkey "^[[B" history-beginning-search-forward-end     # Down

# Turn off all beeps
#unsetopt BEEP
# Turn off autocomplete beeps
unsetopt LIST_BEEP

# Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# Visual Studio Code
PATH="/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$PATH"
